module.exports = () => [
    { domain: "speedtestwe", name: "West Europe", icon: "https://cdn.staticaly.com/gh/hjnilsson/country-flags/master/svg/nl.svg" },
    { domain: "speedtestsea", name: "Southeast Asia", icon: "https://cdn.staticaly.com/gh/hjnilsson/country-flags/master/svg/sg.svg" },
    { domain: "speedtestea", name: "East Asia", icon: "https://cdn.staticaly.com/gh/hjnilsson/country-flags/master/svg/hk.svg" },
    { domain: "speedtestnsus", name: "North Central US", icon: "https://cdn.staticaly.com/gh/hjnilsson/country-flags/master/svg/us.svg" },
    { domain: "speedtestne", name: "North Europe", icon: "https://cdn.staticaly.com/gh/hjnilsson/country-flags/master/svg/ie.svg" },
    { domain: "speedtestscus", name: "South Central US", icon: "https://cdn.staticaly.com/gh/hjnilsson/country-flags/master/svg/us.svg" },
    { domain: "speedtestwus", name: "West US", icon: "https://cdn.staticaly.com/gh/hjnilsson/country-flags/master/svg/us.svg" },
    { domain: "speedtesteus", name: "East US", icon: "https://cdn.staticaly.com/gh/hjnilsson/country-flags/master/svg/us.svg" },
    { domain: "speedtestjpe", name: "Japan East", icon: "https://cdn.staticaly.com/gh/hjnilsson/country-flags/master/svg/jp.svg" },
    { domain: "speedtestjpw", name: "Japan West", icon: "https://cdn.staticaly.com/gh/hjnilsson/country-flags/master/svg/jp.svg" },
    { domain: "speedtestcus", name: "Central US", icon: "https://cdn.staticaly.com/gh/hjnilsson/country-flags/master/svg/us.svg" },
    { domain: "speedtesteus2", name: "East US 2", icon: "https://cdn.staticaly.com/gh/hjnilsson/country-flags/master/svg/us.svg" },
    { domain: "speedtestozse", name: "Australia Southeast", icon: "https://cdn.staticaly.com/gh/hjnilsson/country-flags/master/svg/au.svg" },
    { domain: "speedtestoze", name: "Australia East", icon: "https://cdn.staticaly.com/gh/hjnilsson/country-flags/master/svg/au.svg" },
    { domain: "speedtestukw", name: "West UK", icon: "https://cdn.staticaly.com/gh/hjnilsson/country-flags/master/svg/gb.svg" },
    { domain: "speedtestuks", name: "South UK", icon: "https://cdn.staticaly.com/gh/hjnilsson/country-flags/master/svg/gb.svg" },
    { domain: "speedtestcac", name: "Canada Central", icon: "https://cdn.staticaly.com/gh/hjnilsson/country-flags/master/svg/ca.svg" },
    { domain: "speedtestcae", name: "Canada East", icon: "https://cdn.staticaly.com/gh/hjnilsson/country-flags/master/svg/ca.svg" },
    { domain: "speedtestwestus2", name: "West US 2", icon: "https://cdn.staticaly.com/gh/hjnilsson/country-flags/master/svg/us.svg" },
    { domain: "speedtestwestindia", name: "West India", icon: "https://cdn.staticaly.com/gh/hjnilsson/country-flags/master/svg/in.svg" },
    { domain: "speedtesteastindia", name: "South India", icon: "https://cdn.staticaly.com/gh/hjnilsson/country-flags/master/svg/in.svg" },
    { domain: "speedtestcentralindia", name: "Central India", icon: "https://cdn.staticaly.com/gh/hjnilsson/country-flags/master/svg/in.svg" },
    { domain: "speedtestkoreacentral", name: "Korea Central", icon: "https://cdn.staticaly.com/gh/hjnilsson/country-flags/master/svg/kr.svg" },
    { domain: "speedtestkoreasouth", name: "Korea South", icon: "https://cdn.staticaly.com/gh/hjnilsson/country-flags/master/svg/kr.svg" },
    { domain: "speedtestwestcentralus", name: "West Central US", icon: "https://cdn.staticaly.com/gh/hjnilsson/country-flags/master/svg/us.svg" },
    { domain: "speedtestfrc", name: "France Central", icon: "https://cdn.staticaly.com/gh/hjnilsson/country-flags/master/svg/fr.svg" },
    { domain: "speedtestsan", name: "South Africa North", icon: "https://cdn.staticaly.com/gh/hjnilsson/country-flags/master/svg/za.svg" },
    { domain: "speedtestuaen", name: "UAE North", icon: "https://cdn.staticaly.com/gh/hjnilsson/country-flags/master/svg/ae.svg" },
    { domain: "speedtestden", name: "Germany North", icon: "https://cdn.staticaly.com/gh/hjnilsson/country-flags/master/svg/de.svg" },
    { domain: "speedtestchn", name: "Switzerland North", icon: "https://cdn.staticaly.com/gh/hjnilsson/country-flags/master/svg/ch.svg" },
    { domain: "speedtestchw", name: "Switzerland West", icon: "https://cdn.staticaly.com/gh/hjnilsson/country-flags/master/svg/ch.svg" },
    { domain: "azspeednoeast", name: "Norway East", icon: "https://cdn.staticaly.com/gh/hjnilsson/country-flags/master/svg/no.svg" },
    { domain: "speedtestnea", name: "Brazil", icon: "https://cdn.staticaly.com/gh/hjnilsson/country-flags/master/svg/br.svg" },
    { domain: "speedtestesc", name: "Sweden Central", icon: "https://cdn.staticaly.com/gh/hjnilsson/country-flags/master/svg/se.svg" },
    { domain: "azurespeedtestwestus3", url: "https://azurespeedtestwestus3.z1.web.core.windows.net/", name: "West US 3", icon: "https://cdn.staticaly.com/gh/hjnilsson/country-flags/master/svg/us.svg" },
    { domain: "speedtestqc", url: "https://speedtestqc.z1.web.core.windows.net/", name: "Qatar Central", icon: "https://cdn.staticaly.com/gh/hjnilsson/country-flags/master/svg/qa.svg" }
    //{domain:"cdn", name: "Content Delivery Network *", cdn:true} // CDN does not run on HTTPS, page won't run with mixed content
];
