module.exports = () => [
    { domain: "speedtestwe", name: "West Europe", icon: "nl.svg" },
    { domain: "speedtestsea", name: "Southeast Asia", icon: "sg.svg" },
    { domain: "speedtestea", name: "East Asia", icon: "hk.svg" },
    { domain: "speedtestnsus", name: "North Central US", icon: "us.svg" },
    { domain: "speedtestne", name: "North Europe", icon: "ie.svg" },
    { domain: "speedtestscus", name: "South Central US", icon: "us.svg" },
    { domain: "speedtestwus", name: "West US", icon: "us.svg" },
    { domain: "speedtesteus", name: "East US", icon: "us.svg" },
    { domain: "speedtestjpe", name: "Japan East", icon: "jp.svg" },
    { domain: "speedtestjpw", name: "Japan West", icon: "jp.svg" },
    { domain: "speedtestcus", name: "Central US", icon: "us.svg" },
    { domain: "speedtesteus2", name: "East US 2", icon: "us.svg" },
    { domain: "speedtestozse", name: "Australia Southeast", icon: "au.svg" },
    { domain: "speedtestoze", name: "Australia East", icon: "au.svg" },
    { domain: "speedtestukw", name: "West UK", icon: "gb.svg" },
    { domain: "speedtestuks", name: "South UK", icon: "gb.svg" },
    { domain: "speedtestcac", name: "Canada Central", icon: "ca.svg" },
    { domain: "speedtestcae", name: "Canada East", icon: "ca.svg" },
    { domain: "speedtestwestus2", name: "West US 2", icon: "us.svg" },
    { domain: "speedtestwestindia", name: "West India", icon: "in.svg" },
    { domain: "speedtesteastindia", name: "South India", icon: "in.svg" },
    { domain: "speedtestcentralindia", name: "Central India", icon: "in.svg" },
    { domain: "speedtestkoreacentral", name: "Korea Central", icon: "kr.svg" },
    { domain: "speedtestkoreasouth", name: "Korea South", icon: "kr.svg" },
    { domain: "speedtestwestcentralus", name: "West Central US", icon: "us.svg" },
    { domain: "speedtestfrc", name: "France Central", icon: "fr.svg" },
    { domain: "speedtestsan", name: "South Africa North", icon: "za.svg" },
    { domain: "speedtestuaen", name: "UAE North", icon: "ae.svg" },
    { domain: "speedtestden", name: "Germany North", icon: "de.svg" },
    { domain: "speedtestchn", name: "Switzerland North", icon: "ch.svg" },
    { domain: "speedtestchw", name: "Switzerland West", icon: "ch.svg" },
    { domain: "speedtestene", name: "Norway East", icon: "no.svg" },
    { domain: "speedtestnea", name: "Brazil", icon: "br.svg" },
    { domain: "speedtestesc", name: "Sweden Central", icon: "se.svg" },
    { domain: "azurespeedtestwestus3", url: "https://azurespeedtestwestus3.z1.web.core.windows.net/", name: "West US 3", icon: "us.svg" },
    { domain: "speedtestqc", url: "https://speedtestqc.z1.web.core.windows.net/", name: "Qatar Central", icon: "qa.svg" },
    { domain: "speedtestplc", name: "Poland Central", icon: "pl.svg" },
    { domain: "speedtestitn", url: "https://speedtestitn.z38.web.core.windows.net/cb.json", name: "Italy North", icon: "it.svg" },
    { domain: "speedtestezmla", name: "Los Angeles Edge Zone (preview)", icon: "us.svg" }

    
];
