module.exports = () => [
    { domain: "speedtestmeic", name: "Israel Central", icon: "il.svg" },
    { domain: "speedtestwe", name: "West Europe", icon: "nl.svg" },
    { domain: "speedtestsea", name: "Southeast Asia", icon: "sg.svg" },
    { domain: "speedtestea", name: "East Asia", icon: "hk.svg" },
    { domain: "speedtestnsus", name: "North Central US", icon: "us.svg" },
    { domain: "speedtestne", name: "North Europe", icon: "ie.svg" },
    { domain: "speedtestscus", name: "South Central US", icon: "us.svg" },
    { domain: "speedtestwus", name: "West US", icon: "us.svg" },
    { domain: "speedtesteus", name: "East US", icon: "us.svg" },
    { domain: "speedtestjpe", name: "Japan East", icon: "jp.svg" },
    { domain: "speedtestjpw", name: "Japan West", icon: "jp.svg" },
    { domain: "speedtestcus", name: "Central US", icon: "us.svg" },
    { domain: "speedtesteus2", name: "East US 2", icon: "us.svg" },
    { domain: "speedtestozse", name: "Australia Southeast", icon: "au.svg" },
    { domain: "speedtestoze", name: "Australia East", icon: "au.svg" },
    { domain: "speedtestukw", name: "West UK", icon: "gb.svg" },
    { domain: "speedtestuks", name: "South UK", icon: "gb.svg" },
    { domain: "speedtestcac", name: "Canada Central", icon: "ca.svg" },
    { domain: "speedtestcae", name: "Canada East", icon: "ca.svg" },
    { domain: "speedtestwestus2", name: "West US 2", icon: "us.svg" },
    { domain: "speedtestwestindia", name: "West India", icon: "in.svg" },
    { domain: "speedtesteastindia", name: "South India", icon: "in.svg" },
    { domain: "speedtestcentralindia", name: "Central India", icon: "in.svg" },
    { domain: "speedtestkoreacentral", name: "Korea Central", icon: "kr.svg" },
    { domain: "speedtestkoreasouth", name: "Korea South", icon: "kr.svg" },
    { domain: "speedtestwestcentralus", name: "West Central US", icon: "us.svg" },
    { domain: "speedtestfrc", name: "France Central", icon: "fr.svg" },
    { domain: "speedtestsan", name: "South Africa North", icon: "za.svg" },
    { domain: "speedtestuaen", name: "UAE North", icon: "ae.svg" },
    { domain: "speedtestden", name: "Germany West Central", icon: "de.svg" },
    { domain: "speedtestene", name: "Norway East", icon: "no.svg" },
    { domain: "speedtestnea", name: "Brazil South", icon: "br.svg" },
    { domain: "speedtestesc2", name: "Sweden Central", icon: "se.svg" },
    { domain: "speedtestwus3", url: "https://speedtestwus3.blob.core.windows.net/cb.json", name: "West US 3", icon: "us.svg" },
    { domain: "speedtestaqc", url: "https://speedtestaqc.blob.core.windows.net/cb.json", name: "Qatar Central", icon: "qa.svg" },
    { domain: "speedtestplc", name: "Poland Central", icon: "pl.svg" },
    { domain: "speedtestein", url: "https://speedtestein.blob.core.windows.net/cb.json", name: "Italy North", icon: "it.svg" },
    { domain: "speedtestmmc", url: "https://speedtestmmc.blob.core.windows.net/cb.json", name: "Mexico Central", icon: "mx.svg" },
    { domain: "speedtestapac", url: "https://speedtestapac.blob.core.windows.net/cb.json", name: "Australia Central", icon: "au.svg" },
    { domain: "speedtestjiowest", url: "https://speedtestjiowest.z1.web.core.windows.net/cb.json", name: "Jio India West", icon: "in.svg" },
    { domain: "speedtestesn", url: "https://speedtestesn.blob.core.windows.net/cb.json", name: "Switzerland North", icon: "ch.svg" },
    { domain: "speedtestnzn", url: "https://speedtestnzn.blob.core.windows.net/cb.json", name: "New Zealand North", icon: "nz.svg" }
];
