name: Node CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [24.x]

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install dependencies
      run: npm install
      env:
        CI: true
    - name: Build application
      run: npm run build
      env:
        CI: true
    - name: Test cb.json endpoints
      run: npm run test:endpoints
      env:
        CI: true
        NODE_ENV: production
